server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    enable-self-preservation: false

spring:
  cloud:
    config:
      enabled: false
